name: build

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install npm deps
        run:  npm install -g gatsby-cli
      
      - name: Build
        run: npm run build
